server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # CLAVE ABSOLUTA
    charset utf-8;
    charset_types text/html text/plain text/css application/javascript application/json;

    location / {
        try_files $uri $uri/ =404;
    }
}
